version: '3.9'
services:
  nats-server:
    image: nats:2.10-alpine
    restart: always
    ports:
      - 8222:8222
      - 4222:4222

  gateway:
    build: ./gateway
    restart: always
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    volumes:
      - ./gateway/src:/app/src
    environment:
      - PORT=${GATEWAY_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
    command: npm run start:dev

  products:
    build: ./products
    restart: always
    volumes:
      - ./products/src:/app/src
    environment:
      - PORT=3001
      - DATABASE_URL=${PRODUCT_DATABASE_URL}
      - NATS_SERVERS=${NATS_SERVERS}
    command: npm run start:dev
    depends_on:
      - nats-server

  orders-db:
    restart: always
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${ORDER_DATABASE_USER}
      POSTGRES_PASSWORD: ${ORDER_DATABASE_PASSWORD}
      POSTGRES_DB: ${ORDER_DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data

  orders:
    build: ./orders
    restart: always
    volumes:
      - ./orders/src:/app/src
    environment:
      - PORT=3000
      - DATABASE_URL=${ORDER_DATABASE_URL}
      - NATS_SERVERS=${NATS_SERVERS}
    command: npm run start:dev
    depends_on:
      - nats-server
      - orders-db

  payment:
    build: ./payments
    restart: always
    volumes:
      - ./payments/src:/app/src
    environment:
      - PORT=${PAYMENT_PORT}
      - NATS_SERVERS=${NATS_SERVERS}
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
    command: npm run start:dev
    depends_on:
      - nats-server
